version: "3.1"
services:
  api:
    build: .
    image: abotph-api
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
      DB_URL: "mongodb://mongo:27017"
      DB_NAME: "abotph"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017-27019:27017-27019"
